// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.example.grpc.test;

public interface GrpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GrpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name2 = 1;</code>
   */
  java.lang.String getName2();
  /**
   * <code>string name2 = 1;</code>
   */
  com.google.protobuf.ByteString
      getName2Bytes();
}
