// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.example.grpc.test;

public interface GrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcTest.GrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
