// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.example.grpc.test;

public final class GrpcProto {
  private GrpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_GrpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_GrpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_GrpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_GrpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngrpc.proto\022\004grpc\"\033\n\013GrpcRequest\022\014\n\004nam" +
      "e\030\001 \001(\t\"\035\n\014GrpcResponse\022\r\n\005name2\030\001 \001(\t2<" +
      "\n\013GrpcService\022-\n\004Grpc\022\021.grpc.GrpcRequest" +
      "\032\022.grpc.GrpcResponseB$\n\025com.example.grpc" +
      ".testB\tGrpcProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_GrpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_GrpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_GrpcRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_grpc_GrpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_GrpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_GrpcResponse_descriptor,
        new java.lang.String[] { "Name2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
