// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.example.grpc.test;

public interface GrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
