// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.example.grpc.test;

public final class GrpcProtoTest {
  private GrpcProtoTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcTest_GrpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcTest_GrpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcTest_GrpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcTest_GrpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngrpc.proto\022\010grpcTest\"\036\n\013GrpcRequest\022\017\n" +
      "\007request\030\001 \001(\t\" \n\014GrpcResponse\022\020\n\010respon" +
      "se\030\001 \001(\t2J\n\rGrpcServicePj\0229\n\010GrpcTest\022\025." +
      "grpcTest.GrpcRequest\032\026.grpcTest.GrpcResp" +
      "onseB(\n\025com.example.grpc.testB\rGrpcProto" +
      "TestP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpcTest_GrpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpcTest_GrpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcTest_GrpcRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_grpcTest_GrpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpcTest_GrpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcTest_GrpcResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
